# Generated by Django 4.2.2 on 2023-06-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_servizio_descrizione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servizio',
            name='descrizione',
        ),
        migrations.CreateModel(
            name='Descrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descrizioni', to='info.servizio')),
            ],
        ),
    ]
