# Generated by Django 4.2.2 on 2023-06-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_servizio_descrizione_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descrizione',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
